bin/app.py: 1: bin/app.py: import: not found
bin/app.py: 2: bin/app.py: import: not found
bin/app.py: 8: bin/app.py: Syntax error: "(" unexpected
24.90.221.163:61381 - - [25/May/2017 03:20:39] "HTTP/1.1 GET /trigger" - 200 OK
24.90.221.163:61381 - - [25/May/2017 03:20:40] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
24.90.221.163:61381 - - [25/May/2017 03:20:41] "HTTP/1.1 GET /trigger" - 200 OK
24.90.221.163:61381 - - [25/May/2017 03:20:50] "HTTP/1.1 GET /trigger" - 200 OK
24.90.221.163:61381 - - [25/May/2017 03:20:52] "HTTP/1.1 GET /trigger" - 200 OK
24.90.221.163:62863 - - [25/May/2017 03:28:59] "HTTP/1.1 GET /trigger" - 200 OK
24.90.221.163:62863 - - [25/May/2017 03:29:03] "HTTP/1.1 GET /trigger" - 200 OK
Sending magic packet to 255.255.255.255:9 with 40:16:7E:E8:F9:F0
24.90.221.163:53605 - - [25/May/2017 03:30:13] "HTTP/1.1 GET /trigger" - 200 OK
24.90.221.163:53605 - - [25/May/2017 03:30:14] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
Sending magic packet to 255.255.255.255:9 with 40:16:7E:E8:F9:F0
24.90.221.163:53605 - - [25/May/2017 03:30:20] "HTTP/1.1 GET /trigger" - 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 236, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 227, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 409, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 384, in handle_class
    return tocall(*args)
  File "/home/pi/iftttmaker/site/bin/app.py", line 22, in GET
    subprocess.call("scripts/%s.sh" % form.scriptname)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

24.90.221.163:53713 - - [25/May/2017 03:39:04] "HTTP/1.1 GET /trigger" - 500 Internal Server Error
Sending magic packet to 10.0.1.15:9 with 40:16:7E:E8:F9:F0
24.90.221.163:53713 - - [25/May/2017 03:39:08] "HTTP/1.1 GET /trigger" - 200 OK
Sending magic packet to 10.0.1.15:9 with 40:16:7E:E8:F9:F0
24.90.221.163:53713 - - [25/May/2017 03:39:11] "HTTP/1.1 GET /trigger" - 200 OK
Sending magic packet to 10.0.1.15:9 with 40:16:7E:E8:F9:F0
24.90.221.163:53717 - - [25/May/2017 03:39:43] "HTTP/1.1 GET /trigger" - 200 OK
Sending magic packet to 255.255.255.255:9 with 40:16:7E:E8:F9:F0
24.90.221.163:53986 - - [25/May/2017 03:58:16] "HTTP/1.1 GET /trigger" - 200 OK
Sending magic packet to 255.255.255.255:9 with 40:16:7E:E8:F9:F0
54.234.251.220:35560 - - [25/May/2017 04:00:31] "HTTP/1.1 GET /trigger" - 200 OK
Sending magic packet to 255.255.255.255:9 with 40:16:7E:E8:F9:F0
52.86.0.60:45656 - - [25/May/2017 04:00:32] "HTTP/1.1 GET /trigger" - 200 OK
24.90.221.163:50446 - - [25/May/2017 04:07:43] "HTTP/1.1 GET /aircon" - 200 OK
24.90.221.163:50446 - - [25/May/2017 04:07:43] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
24.90.221.163:50446 - - [25/May/2017 04:07:55] "HTTP/1.1 GET /aircon" - 200 OK
54.243.5.83:45168 - - [25/May/2017 04:08:06] "HTTP/1.1 GET /trigger" - 200 OK
54.234.251.220:54398 - - [25/May/2017 04:09:41] "HTTP/1.1 GET /aircon" - 200 OK
34.207.162.140:52836 - - [25/May/2017 04:12:46] "HTTP/1.1 GET /aircon" - 200 OK
34.207.162.140:53654 - - [25/May/2017 04:13:11] "HTTP/1.1 GET /aircon" - 200 OK
54.162.98.138:58266 - - [25/May/2017 04:13:22] "HTTP/1.1 GET /aircon" - 200 OK
54.243.5.83:40930 - - [25/May/2017 04:19:57] "HTTP/1.1 GET /aircon" - 200 OK
54.243.5.83:41634 - - [25/May/2017 04:20:15] "HTTP/1.1 GET /aircon" - 200 OK
52.86.0.60:56432 - - [25/May/2017 04:20:21] "HTTP/1.1 GET /aircon" - 200 OK
34.207.162.140:45670 - - [25/May/2017 04:20:32] "HTTP/1.1 GET /aircon" - 200 OK
54.243.5.83:44464 - - [25/May/2017 04:21:49] "HTTP/1.1 GET /aircon" - 200 OK
54.243.5.83:45062 - - [25/May/2017 04:22:10] "HTTP/1.1 GET /aircon" - 200 OK
52.86.0.60:46486 - - [25/May/2017 04:22:39] "HTTP/1.1 GET /aircon" - 200 OK
54.162.98.138:60042 - - [25/May/2017 04:23:13] "HTTP/1.1 GET /aircon" - 200 OK
54.162.98.138:36058 - - [25/May/2017 04:23:59] "HTTP/1.1 GET /aircon" - 200 OK
54.162.98.138:39730 - - [25/May/2017 04:24:26] "HTTP/1.1 GET /aircon" - 200 OK
52.86.0.60:36134 - - [25/May/2017 04:25:17] "HTTP/1.1 GET /aircon" - 200 OK
34.207.162.140:32928 - - [25/May/2017 04:25:41] "HTTP/1.1 GET /aircon" - 200 OK
54.162.98.138:48046 - - [25/May/2017 04:26:07] "HTTP/1.1 GET /aircon" - 200 OK
54.234.251.220:59104 - - [25/May/2017 04:26:57] "HTTP/1.1 GET /aircon" - 200 OK
52.86.0.60:50590 - - [25/May/2017 04:30:57] "HTTP/1.1 GET /aircon" - 200 OK
34.207.162.140:49812 - - [25/May/2017 04:31:20] "HTTP/1.1 GET /aircon" - 200 OK
54.82.245.190:35180 - - [25/May/2017 05:05:09] "HTTP/1.1 GET /aircon" - 200 OK
54.82.245.190:35928 - - [25/May/2017 05:05:22] "HTTP/1.1 GET /aircon" - 200 OK
54.234.251.220:51564 - - [25/May/2017 05:05:35] "HTTP/1.1 GET /aircon" - 200 OK
54.162.98.138:48538 - - [25/May/2017 05:13:29] "HTTP/1.1 GET /aircon" - 200 OK
54.82.245.190:34648 - - [25/May/2017 05:13:41] "HTTP/1.1 GET /aircon" - 200 OK
bin/app.py: 1: bin/app.py: import: not found
bin/app.py: 2: bin/app.py: import: not found
bin/app.py: 3: bin/app.py: import: not found
bin/app.py: 7: bin/app.py: Syntax error: "(" unexpected
bin/app.py: 1: bin/app.py: import: not found
bin/app.py: 2: bin/app.py: import: not found
bin/app.py: 3: bin/app.py: import: not found
bin/app.py: 7: bin/app.py: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 236, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 227, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 409, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 384, in handle_class
    return tocall(*args)
  File "/home/pi/iftttmaker/site/bin/app.py", line 25, in GET
    subprocess.call("scripts/%s.sh" % form.scriptname)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

24.90.221.163:52702 - - [26/May/2017 05:25:11] "HTTP/1.1 GET /trigger" - 500 Internal Server Error
24.90.221.163:52728 - - [26/May/2017 05:25:36] "HTTP/1.1 GET /aircon" - 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 236, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 227, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 409, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 384, in handle_class
    return tocall(*args)
  File "/home/pi/iftttmaker/site/bin/app.py", line 25, in GET
    subprocess.call("scripts/%s.sh" % form.scriptname)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

24.90.221.163:52755 - - [26/May/2017 05:25:57] "HTTP/1.1 GET /trigger" - 500 Internal Server Error
52.86.0.60:47106 - - [26/May/2017 05:27:19] "HTTP/1.1 GET /aircon" - 200 OK
52.86.0.60:33620 - - [26/May/2017 05:29:10] "HTTP/1.1 GET /aircon" - 200 OK
24.90.221.163:63746 - - [26/May/2017 05:34:36] "HTTP/1.1 GET /aircon" - 200 OK
24.90.221.163:63746 - - [26/May/2017 05:34:37] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
